tasks:
  - name: init mattermost
    command: cd mattermost && docker compose up -d && sh init.sh

  - name: init serge
    command: cd serge && docker compose up -d

  - name: init ai-bot
    command: cd ai-bot && docker compose up -d
ports:
  - name: mattermost
    port: 8065
    onOpen: open-browser
  - name: serge
    port: 8008
    onOpen: open-browser
  - name: ai-bot
    port: 9000
    onOpen: ignore
