tasks:
  - name: init mattermost
    command: cd mattermost && docker compose up -d

  - name: init serge
    command: cd serge && docker compose up -d

  - name: init ai-bot
    command: cd ai-bot && docker compose up -d
ports:
  - name: mattermost
    port: 8065
    onOpen: open-browser
  - name: serge
    port: 8080
    onOpen: open-browser
