tasks:
  - name: mattermost
    command: export GPSITEURL=$(gp url 8065) && sed -i "s@__GPSITEURL__@$GPSITEURL@" docker-compose.yml && docker compose up -d && sh init.sh
ports:
  - name: mattermost
    port: 8065
    onOpen: open-browser
  - name: serge
    port: 8008
    onOpen: open-browser
  - name: ai-bot
    port: 9000
    onOpen: ignore
